# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/os/Desktop/Face-Detection-master

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/os/Desktop/Face-Detection-master

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/os/Desktop/Face-Detection-master/CMakeFiles /home/os/Desktop/Face-Detection-master/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/os/Desktop/Face-Detection-master/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named FaceDetection

# Build rule for target.
FaceDetection: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FaceDetection
.PHONY : FaceDetection

# fast build rule for target.
FaceDetection/fast:
	$(MAKE) -f CMakeFiles/FaceDetection.dir/build.make CMakeFiles/FaceDetection.dir/build
.PHONY : FaceDetection/fast

#=============================================================================
# Target rules for targets named HaarDetection

# Build rule for target.
HaarDetection: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 HaarDetection
.PHONY : HaarDetection

# fast build rule for target.
HaarDetection/fast:
	$(MAKE) -f CMakeFiles/HaarDetection.dir/build.make CMakeFiles/HaarDetection.dir/build
.PHONY : HaarDetection/fast

FaceDetection.o: FaceDetection.cpp.o
.PHONY : FaceDetection.o

# target to build an object file
FaceDetection.cpp.o:
	$(MAKE) -f CMakeFiles/FaceDetection.dir/build.make CMakeFiles/FaceDetection.dir/FaceDetection.cpp.o
.PHONY : FaceDetection.cpp.o

FaceDetection.i: FaceDetection.cpp.i
.PHONY : FaceDetection.i

# target to preprocess a source file
FaceDetection.cpp.i:
	$(MAKE) -f CMakeFiles/FaceDetection.dir/build.make CMakeFiles/FaceDetection.dir/FaceDetection.cpp.i
.PHONY : FaceDetection.cpp.i

FaceDetection.s: FaceDetection.cpp.s
.PHONY : FaceDetection.s

# target to generate assembly for a file
FaceDetection.cpp.s:
	$(MAKE) -f CMakeFiles/FaceDetection.dir/build.make CMakeFiles/FaceDetection.dir/FaceDetection.cpp.s
.PHONY : FaceDetection.cpp.s

HaarDetection.o: HaarDetection.cpp.o
.PHONY : HaarDetection.o

# target to build an object file
HaarDetection.cpp.o:
	$(MAKE) -f CMakeFiles/HaarDetection.dir/build.make CMakeFiles/HaarDetection.dir/HaarDetection.cpp.o
.PHONY : HaarDetection.cpp.o

HaarDetection.i: HaarDetection.cpp.i
.PHONY : HaarDetection.i

# target to preprocess a source file
HaarDetection.cpp.i:
	$(MAKE) -f CMakeFiles/HaarDetection.dir/build.make CMakeFiles/HaarDetection.dir/HaarDetection.cpp.i
.PHONY : HaarDetection.cpp.i

HaarDetection.s: HaarDetection.cpp.s
.PHONY : HaarDetection.s

# target to generate assembly for a file
HaarDetection.cpp.s:
	$(MAKE) -f CMakeFiles/HaarDetection.dir/build.make CMakeFiles/HaarDetection.dir/HaarDetection.cpp.s
.PHONY : HaarDetection.cpp.s

Image.o: Image.cpp.o
.PHONY : Image.o

# target to build an object file
Image.cpp.o:
	$(MAKE) -f CMakeFiles/HaarDetection.dir/build.make CMakeFiles/HaarDetection.dir/Image.cpp.o
.PHONY : Image.cpp.o

Image.i: Image.cpp.i
.PHONY : Image.i

# target to preprocess a source file
Image.cpp.i:
	$(MAKE) -f CMakeFiles/HaarDetection.dir/build.make CMakeFiles/HaarDetection.dir/Image.cpp.i
.PHONY : Image.cpp.i

Image.s: Image.cpp.s
.PHONY : Image.s

# target to generate assembly for a file
Image.cpp.s:
	$(MAKE) -f CMakeFiles/HaarDetection.dir/build.make CMakeFiles/HaarDetection.dir/Image.cpp.s
.PHONY : Image.cpp.s

Pgm.o: Pgm.cpp.o
.PHONY : Pgm.o

# target to build an object file
Pgm.cpp.o:
	$(MAKE) -f CMakeFiles/HaarDetection.dir/build.make CMakeFiles/HaarDetection.dir/Pgm.cpp.o
.PHONY : Pgm.cpp.o

Pgm.i: Pgm.cpp.i
.PHONY : Pgm.i

# target to preprocess a source file
Pgm.cpp.i:
	$(MAKE) -f CMakeFiles/HaarDetection.dir/build.make CMakeFiles/HaarDetection.dir/Pgm.cpp.i
.PHONY : Pgm.cpp.i

Pgm.s: Pgm.cpp.s
.PHONY : Pgm.s

# target to generate assembly for a file
Pgm.cpp.s:
	$(MAKE) -f CMakeFiles/HaarDetection.dir/build.make CMakeFiles/HaarDetection.dir/Pgm.cpp.s
.PHONY : Pgm.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... FaceDetection"
	@echo "... HaarDetection"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... FaceDetection.o"
	@echo "... FaceDetection.i"
	@echo "... FaceDetection.s"
	@echo "... HaarDetection.o"
	@echo "... HaarDetection.i"
	@echo "... HaarDetection.s"
	@echo "... Image.o"
	@echo "... Image.i"
	@echo "... Image.s"
	@echo "... Pgm.o"
	@echo "... Pgm.i"
	@echo "... Pgm.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

